// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqhjdvpgbdprglepatfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxaGpkdnBnYmRwcmdsZXBhdGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4NjUwODUsImV4cCI6MjEwMzQ0MTA4NX0.Ded8X88RIX73BVxyjHUV1vN7yQEUuiy-makdkvIHDBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});